var annotated_dup =
[
    [ "Core", null, [
      [ "Alarm_Event_t", "structCore_1_1Alarm__Event__t.html", "structCore_1_1Alarm__Event__t" ],
      [ "AlarmEvent_t", "structCore_1_1AlarmEvent__t.html", "structCore_1_1AlarmEvent__t" ],
      [ "CEO", "classCore_1_1CEO.html", "classCore_1_1CEO" ],
      [ "CommunicationManager", "classCore_1_1CommunicationManager.html", "classCore_1_1CommunicationManager" ],
      [ "DataManager", "classCore_1_1DataManager.html", "classCore_1_1DataManager" ],
      [ "IManager", "classCore_1_1IManager.html", null ],
      [ "StorageManager", "classCore_1_1StorageManager.html", "classCore_1_1StorageManager" ],
      [ "TaskMonitor", "classCore_1_1TaskMonitor.html", "classCore_1_1TaskMonitor" ],
      [ "TimeManager", "classCore_1_1TimeManager.html", "classCore_1_1TimeManager" ]
    ] ],
    [ "Hardware", null, [
      [ "ActuatorManager", "classHardware_1_1ActuatorManager.html", "classHardware_1_1ActuatorManager" ],
      [ "Bme280Sensor", "classHardware_1_1Bme280Sensor.html", "classHardware_1_1Bme280Sensor" ],
      [ "BusManager", "classHardware_1_1BusManager.html", "classHardware_1_1BusManager" ],
      [ "DS3231", "classHardware_1_1DS3231.html", null ],
      [ "ExampleTempSensor", "classHardware_1_1ExampleTempSensor.html", "classHardware_1_1ExampleTempSensor" ],
      [ "I2CBus", "classHardware_1_1I2CBus.html", "classHardware_1_1I2CBus" ],
      [ "I2CExpanderActuator", "classHardware_1_1I2CExpanderActuator.html", "classHardware_1_1I2CExpanderActuator" ],
      [ "IActuator", "classHardware_1_1IActuator.html", "classHardware_1_1IActuator" ],
      [ "ISensor", "classHardware_1_1ISensor.html", "classHardware_1_1ISensor" ],
      [ "ITimeSource", "classHardware_1_1ITimeSource.html", "classHardware_1_1ITimeSource" ],
      [ "PinCapabilities", "classHardware_1_1PinCapabilities.html", null ],
      [ "PinManager", "classHardware_1_1PinManager.html", "classHardware_1_1PinManager" ],
      [ "PinMap", "classHardware_1_1PinMap.html", null ],
      [ "RelayActuator", "classHardware_1_1RelayActuator.html", "classHardware_1_1RelayActuator" ],
      [ "SensorManager", "classHardware_1_1SensorManager.html", "classHardware_1_1SensorManager" ],
      [ "SPIBus", "classHardware_1_1SPIBus.html", "classHardware_1_1SPIBus" ],
      [ "UARTBus", "classHardware_1_1UARTBus.html", "classHardware_1_1UARTBus" ]
    ] ],
    [ "Tools", null, [
      [ "ToolBox", "classTools_1_1ToolBox.html", "classTools_1_1ToolBox" ]
    ] ],
    [ "_vfs_littlefs_file_t", "struct__vfs__littlefs__file__t.html", "struct__vfs__littlefs__file__t" ],
    [ "lfs", "structlfs.html", "structlfs" ],
    [ "lfs_attr", "structlfs__attr.html", null ],
    [ "lfs_cache", "structlfs__cache.html", null ],
    [ "lfs_commit", "structlfs__commit.html", null ],
    [ "lfs_config", "structlfs__config.html", null ],
    [ "lfs_dir", "structlfs__dir.html", null ],
    [ "lfs_dir_commit_commit", "structlfs__dir__commit__commit.html", null ],
    [ "lfs_dir_find_match", "structlfs__dir__find__match.html", null ],
    [ "lfs_dir_traverse", "structlfs__dir__traverse.html", null ],
    [ "lfs_diskoff", "structlfs__diskoff.html", null ],
    [ "lfs_fcrc", "structlfs__fcrc.html", null ],
    [ "lfs_file", "structlfs__file.html", "structlfs__file" ],
    [ "lfs_file_config", "structlfs__file__config.html", null ],
    [ "lfs_fs_parent_match", "structlfs__fs__parent__match.html", null ],
    [ "lfs_fsinfo", "structlfs__fsinfo.html", null ],
    [ "lfs_gstate", "structlfs__gstate.html", null ],
    [ "lfs_info", "structlfs__info.html", null ],
    [ "lfs_mattr", "structlfs__mattr.html", null ],
    [ "lfs_mdir", "structlfs__mdir.html", null ],
    [ "lfs_superblock", "structlfs__superblock.html", null ],
    [ "lfs_tortoise_t", "structlfs__tortoise__t.html", null ],
    [ "vfs_littlefs_dir_t", "structvfs__littlefs__dir__t.html", "structvfs__littlefs__dir__t" ]
];